version: "3.9"

services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sbsys
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  app:
    container_name: test-dipity-backend
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "4000:8080"
    links:
      - db
    volumes:
      - .:/home/app
      - /home/app/node_modules
    restart: always

volumes:
  mongo-data:
    driver: local
